export const environmentalParametersMonitorData = [
    {
        "type": "section",
        "content": "A. Sample Matrix / Group of Water and Wastewater"
    },
    {
        "type": "section",
        "content": "(a) Physical Tests"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Temperature",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Colour",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "No",
        "rlab_thane": "Yes",
        "rlab_nashik": "No",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "3",
        "parameter": "pH",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "4",
        "parameter": "Turbidity",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "5",
        "parameter": "Conductivity",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "6",
        "parameter": "Total Solids",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "7",
        "parameter": "Total Dissolved Solids (TDS)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "8",
        "parameter": "Total Suspended Solids (TSS)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "section",
        "content": "(b) Inorganic Tests"
    },
    {
        "type": "section",
        "content": "(i) General & Non-metallic"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Alkalinity",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Chloride",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "3",
        "parameter": "Cyanide",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "4",
        "parameter": "Dissolved oxygen",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "5",
        "parameter": "Nitrite nitrogen",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "6",
        "parameter": "Nitrate nitrogen",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "7",
        "parameter": "Ammonical nitrogen",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "8",
        "parameter": "Fluoride",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "9",
        "parameter": "Hardness (Total)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "10",
        "parameter": "Calcium",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "11",
        "parameter": "Magnesium",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "12",
        "parameter": "Phosphate",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "13",
        "parameter": "Sulphate",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "14",
        "parameter": "Sulphide",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "15",
        "parameter": "Total Residual chlorine (TRC)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "section",
        "content": "(ii) Trace Metals Tests"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Aluminium (Al)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "No",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Arsenic (As) Total",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "3",
        "parameter": "Barium",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "No",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "4",
        "parameter": "Boron",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "5",
        "parameter": "Chromium (Cr) Hexavalent",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "6",
        "parameter": "Chromium (Cr) Total",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "7",
        "parameter": "Cadmium (Cd)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "8",
        "parameter": "Cobalt (Co)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "9",
        "parameter": "Copper (Cu)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "10",
        "parameter": "Iron (Fe)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "11",
        "parameter": "Lead (Pb)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "12",
        "parameter": "Manganese (Mn)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "13",
        "parameter": "Mercury (Hg)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "14",
        "parameter": "Nickel (Ni)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "15",
        "parameter": "Potassium (K)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "16",
        "parameter": "Sodium (Na)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "17",
        "parameter": "Vanadium (V)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "Yes",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "18",
        "parameter": "Zinc (Zn)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "19",
        "parameter": "Selenium (Se)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "No",
        "rlab_thane": "Yes",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "section",
        "content": "(c) Organics (General) and Trace Organics Tests"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Biological Oxygen Demand (BOD)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Chemical oxygen demand (COD)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "3",
        "parameter": "Oil & Grease",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "4",
        "parameter": "Phenolic Compounds as C6H5OH",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "5",
        "parameter": "Benzopyrene",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "6",
        "parameter": "Pesticides",
        "central_lab_mahape": "",
        "rlab_csn": "",
        "rlab_pune": "",
        "rlab_thane": "",
        "rlab_nashik": "",
        "rlab_chiplun": "",
        "rlab_chandrapur": "",
        "rlab_nagpur": ""
    },
    {
        "type": "data",
        "s_no": "6.a",
        "parameter": "Organochlorine Pesticides (OCPs) Tests",
        "central_lab_mahape": "",
        "rlab_csn": "",
        "rlab_pune": "",
        "rlab_thane": "",
        "rlab_nashik": "",
        "rlab_chiplun": "",
        "rlab_chandrapur": "",
        "rlab_nagpur": ""
    },
    {
        "type": "data",
        "s_no": "i",
        "parameter": "Aldrin",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "ii",
        "parameter": "Alpha Endosulphan",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "iii",
        "parameter": "p,p’-DDT",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "iv",
        "parameter": "Alpha-HCH",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "v",
        "parameter": "Beta HCH",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "vi",
        "parameter": "Beta Endosulphan",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "vii",
        "parameter": "Gama-HCH",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "viii",
        "parameter": "o,p’-DDT",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "ix",
        "parameter": "p,p’-DDE",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "6.b",
        "parameter": "Organophosphorus Pesticides (OPPs) Tests",
        "central_lab_mahape": "",
        "rlab_csn": "",
        "rlab_pune": "",
        "rlab_thane": "",
        "rlab_nashik": "",
        "rlab_chiplun": "",
        "rlab_chandrapur": "",
        "rlab_nagpur": ""
    },
    {
        "type": "data",
        "s_no": "i",
        "parameter": "Malathion",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "ii",
        "parameter": "Methyl parathion",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "iii",
        "parameter": "Chlorpyriphos",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "iv",
        "parameter": "Dimethoate",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "v",
        "parameter": "Dieldrin",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "vi",
        "parameter": "Ethion",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "section",
        "content": "(d) Microbiological Tests"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Total Coliform",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Faecal Coliform",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "3",
        "parameter": "E. Coli",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "4",
        "parameter": "Faecal Streptococci",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "section",
        "content": "(e) Toxicological Tests"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Bioassay method for evaluation of toxicity using fish (90% survival of fish after 96 hrs in 100% effluent)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "section",
        "content": "B. Sample Matrix / Group of Solid / Solid Waste"
    },
    {
        "type": "section",
        "content": "(a) Soil / Sediment / Compost Tests"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Cation Exchange Capacity (CEC)",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Electrical Conductivity (EC)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "3",
        "parameter": "Organic carbon (Chemical Method )",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "4",
        "parameter": "pH",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "5",
        "parameter": "Soil moisture",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "6",
        "parameter": "Total nitrogen",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "7",
        "parameter": "Metals by digestion (As, Cd, Cr, Pb, Ni etc.)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "section",
        "content": "(b) Hazardous Waste (Liquid / Slurry / Sludge / Solid / Semi-Solid) Tests"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Corrosivity",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Ignitability (Flash Point)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "3",
        "parameter": "Loss on Drying at 1050C (% Moisture Content)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "4",
        "parameter": "Loss on Drying at 5500C (% Organic Content)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "5",
        "parameter": "pH",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "6",
        "parameter": "Organic carbon/matter (Chemical Method )",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "7",
        "parameter": "Calorific Value",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "8",
        "parameter": "Toxicity Characteristics leaching procedure (TCLP) Leachate and Metals in Leachate (As,Cd,Cr, Pb, Ni)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "section",
        "content": "C. Sample Matrix / Group of Analytes: Air"
    },
    {
        "type": "section",
        "content": "(a) Ambient Air"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Nitrogen dioxide as NO2",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Sulphur dioxide (SO2)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "3",
        "parameter": "Particulate matter (PM10)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "4",
        "parameter": "Particulate matter (PM2.5)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "5",
        "parameter": "Carbon Monoxide",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "6",
        "parameter": "Ozone",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "7",
        "parameter": "Benzene",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "8",
        "parameter": "Ammonia",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "9",
        "parameter": "Metals in Particulate Matter, Pb",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "10",
        "parameter": "Metals in Particulate Matter, As",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "11",
        "parameter": "Metals in Particulate Matter, Ni",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "12",
        "parameter": "Particulate Benzo-a-Pyrene (BaP)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "section",
        "content": "(b) Stack Gas / Stationary Source Emission"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Particulate Matter",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Sulphur Dioxide",
        "central_lab_mahape": "Yes",
        "rlab_csn": "Yes",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "Yes"
    },
    {
        "type": "data",
        "s_no": "3",
        "parameter": "Carbon Dioxide",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "4",
        "parameter": "Carbon Monoxide (NDIR based Method)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "5",
        "parameter": "Temperature",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "6",
        "parameter": "Moisture",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "Yes",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "7",
        "parameter": "Oxygen",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "8",
        "parameter": "Oxides of Nitrogen",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "No",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "9",
        "parameter": "Halides (HCL/HF)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "section",
        "content": "(c) Noise Level"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Ambient Noise level measurement (20 to 140 dB)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "Yes",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Source Noise Level Measurement (Industrial process, DG set- 20 to 140dB)",
        "central_lab_mahape": "Yes",
        "rlab_csn": "No",
        "rlab_pune": "Yes",
        "rlab_thane": "Yes",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "section",
        "content": "(d) Meteorological Monitoring"
    },
    {
        "type": "data",
        "s_no": "1",
        "parameter": "Ambient Temperature",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "2",
        "parameter": "Wind direction",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "3",
        "parameter": "Wind speed",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "4",
        "parameter": "Relative Humidity",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    },
    {
        "type": "data",
        "s_no": "5",
        "parameter": "Mixing Height",
        "central_lab_mahape": "No",
        "rlab_csn": "No",
        "rlab_pune": "No",
        "rlab_thane": "No",
        "rlab_nashik": "No",
        "rlab_chiplun": "No",
        "rlab_chandrapur": "Yes",
        "rlab_nagpur": "No"
    }
];
