export const labEquipmentData = [
    {
        "s_no": 1,
        "instrument_name": "Ammonia distillation assembly/TKN Analyzer",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 2,
        "instrument_name": "Aquarium for Toxicity bioassay test with complete accessories (*4 Nos)",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "No",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 6
    },
    {
        "s_no": 3,
        "instrument_name": "Autoclave (*2 Nos)",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 4,
        "instrument_name": "Bacteriological Incubators Stainless steel (*2 Nos)",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 7
    },
    {
        "s_no": 5,
        "instrument_name": "BOD Incubators (2 nos.)",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "YES",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 6,
        "instrument_name": "Centrifuge",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "No",
        "chiplun_lab": "No",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 2
    },
    {
        "s_no": 7,
        "instrument_name": "COD Digestion heated Blocks (2) with capacity 16 nos. or more",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 8,
        "instrument_name": "Cyanide Distillation Assembly (3)",
        "central_lab": "YES",
        "csn_lab": "No",
        "pune_lab": "No.",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "No",
        "chandrapur_lab": "---",
        "nagpur_lab": "Yes",
        "total": 3
    },
    {
        "s_no": 9,
        "instrument_name": "Deep Freezer- Capacity 500 litre",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 7
    },
    {
        "s_no": 10,
        "instrument_name": "Laminar Flow bench for Microbiological analysis",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 7
    },
    {
        "s_no": 11,
        "instrument_name": "Magnetic Stirrer with heating system (*2 Nos)",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 12,
        "instrument_name": "Mechanical Shaker",
        "central_lab": "YES",
        "csn_lab": "No",
        "pune_lab": "Yes",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 5
    },
    {
        "s_no": 13,
        "instrument_name": "Microbial culture refrigerator",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "No",
        "thane_lab": "Yes",
        "nashik_lab": "No",
        "chiplun_lab": "No",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 3
    },
    {
        "s_no": 14,
        "instrument_name": "Microwave Digester with 16 vessels/ Hot Plate",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 15,
        "instrument_name": "Muffle Furnace (*1 Nos), Range 1200 C",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 16,
        "instrument_name": "Phenol distillation assembly (3)",
        "central_lab": "YES",
        "csn_lab": "No",
        "pune_lab": "Yes",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 4
    },
    {
        "s_no": 17,
        "instrument_name": "Plate counter, Manual/Automatic",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 7
    },
    {
        "s_no": 18,
        "instrument_name": "Digestion Chambers/ Fume hood",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 4
    },
    {
        "s_no": 19,
        "instrument_name": "Digital Thermometer & Humidity meter- All lab area",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 20,
        "instrument_name": "Dispensers (Various capacities ) up to 5, 10, 25 & 50 ml",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 21,
        "instrument_name": "Filtration Assembly with vacuum pump",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 22,
        "instrument_name": "Fluoride Distillation Assembly (3)",
        "central_lab": "YES",
        "csn_lab": "No",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "No",
        "chandrapur_lab": "---",
        "nagpur_lab": "No",
        "total": 2
    },
    {
        "s_no": 23,
        "instrument_name": "Arsenic / Fluoride Glass Distillation assemblies",
        "central_lab": "YES",
        "csn_lab": "No",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "No",
        "chiplun_lab": "No",
        "chandrapur_lab": "----",
        "nagpur_lab": "No",
        "total": 1
    },
    {
        "s_no": 24,
        "instrument_name": "Glass Double Distillation Assembly /Water Purification System",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 25,
        "instrument_name": "Heating mantles (2 nos.)",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 4
    },
    {
        "s_no": 26,
        "instrument_name": "Hot plates (small, Medium and Large )  (*2 nos.)",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 27,
        "instrument_name": "Thermo Hygrometer",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 28,
        "instrument_name": "Top loading Precision Digital Balance (minimum detection 0.001mg/0.01 mg) with anti-vibration facility-",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 29,
        "instrument_name": "Refrigerators Big Size 300 litres or more, double door- 2 nos.",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 30,
        "instrument_name": "Rotary Evaporator (Buchi type)  with water recirculating chiller",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "No",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 3
    },
    {
        "s_no": 31,
        "instrument_name": "Separating funnel shaker",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "No",
        "nashik_lab": "No",
        "chiplun_lab": "No",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 3
    },
    {
        "s_no": 32,
        "instrument_name": "Soxhlet Apparatus",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "No",
        "chiplun_lab": "No",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "No",
        "total": 3
    },
    {
        "s_no": 33,
        "instrument_name": "Thermometer (Alcohol)",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "No",
        "chandrapur_lab": "---",
        "nagpur_lab": "No",
        "total": 3
    },
    {
        "s_no": 34,
        "instrument_name": "Dry & wet bulb  Thermometer",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "No",
        "chandrapur_lab": "---",
        "nagpur_lab": "No",
        "total": 3
    },
    {
        "s_no": 35,
        "instrument_name": "Toxicity characteristic leaching procedure (TCLP) Extractors (Zero head and Bottle)",
        "central_lab": "No",
        "csn_lab": "Yes",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "No",
        "chandrapur_lab": "----",
        "nagpur_lab": "No",
        "total": 2
    },
    {
        "s_no": 36,
        "instrument_name": "Ultra sonic water bath- Capacity 3 litre",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 37,
        "instrument_name": "Water Bath with temperature control (*2 Nos)",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 38,
        "instrument_name": "Atomic Absorption spectrometer (AAS)- Flame, Hydride & Graphite Tube Atomizer (GTA)",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 39,
        "instrument_name": "Analytical Balance 4/5 digit & 6 digit (Digital)",
        "central_lab": "YES",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 40,
        "instrument_name": "Binocular Stereo Zoom Microscope",
        "central_lab": "Yes",
        "csn_lab": "No",
        "pune_lab": "No",
        "thane_lab": "Yes",
        "nashik_lab": "No",
        "chiplun_lab": "No",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 2
    },
    {
        "s_no": 41,
        "instrument_name": "Bomb Calorimeter",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 7
    },
    {
        "s_no": 42,
        "instrument_name": "Colony counter",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 43,
        "instrument_name": "Conductivity meter- 2 nos.",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 44,
        "instrument_name": "Digital Burettes- 50 ml*2",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 45,
        "instrument_name": "Dissolved Oxygen Meter (Bench model)",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 7
    },
    {
        "s_no": 46,
        "instrument_name": "Flame Photometer",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "No",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 6
    },
    {
        "s_no": 47,
        "instrument_name": "Flash Point Apparatus",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 7
    },
    {
        "s_no": 48,
        "instrument_name": "Gas Chromatograph Mass Spectrometer",
        "central_lab": "Yes",
        "csn_lab": "No",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "No",
        "chiplun_lab": "No",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 1
    },
    {
        "s_no": 49,
        "instrument_name": "High Performance Liquid Chromatograph (HPLC)",
        "central_lab": "No",
        "csn_lab": "No",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "No",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 1
    },
    {
        "s_no": 50,
        "instrument_name": "Nephelometer (Turbidity Meter)",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 51,
        "instrument_name": "pH-Meter with combined electrode (3 point)- 2 nos.",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 52,
        "instrument_name": "Specific ion Analyzer with ion selective electrodes",
        "central_lab": "Yes",
        "csn_lab": "No",
        "pune_lab": "No",
        "thane_lab": "Yes",
        "nashik_lab": "No",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 4
    },
    {
        "s_no": 53,
        "instrument_name": "TKN Analyzer semi-automatic with aluminum block digester",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 54,
        "instrument_name": "UV-Vis Spectrophotometer",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "Yes",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "Yes",
        "nagpur_lab": "Yes",
        "total": 8
    },
    {
        "s_no": 55,
        "instrument_name": "Carbon, Hydrogen, Nitrogen and Sulphur (CHNS) Elemental Analyzer",
        "central_lab": "Yes",
        "csn_lab": "Yes",
        "pune_lab": "Yes",
        "thane_lab": "No",
        "nashik_lab": "Yes",
        "chiplun_lab": "Yes",
        "chandrapur_lab": "No",
        "nagpur_lab": "Yes",
        "total": 6
    },
    {
        "s_no": 56,
        "instrument_name": "Inductively Coupled Plasma Mass (ICP-MS) Spectrometer",
        "central_lab": "Yes",
        "csn_lab": "No",
        "pune_lab": "No",
        "thane_lab": "No",
        "nashik_lab": "No",
        "chiplun_lab": "No",
        "chandrapur_lab": "No",
        "nagpur_lab": "No",
        "total": 1
    }
];
